### ISSUE TITLE
Plot creation

### ISSUE THREAD

**Issue by R-G-1** [evmckinney9/transpile_benchy#9]
### Feature Description and Why

There should be control in the creation of plots. An example is to be able to put two different metrics on the same graph.

**Comment by evmckinney9** [comment]
Main logic of the current plotting function is to separate the legend into a subplot. This preservers the aspect ratio of the plots when the legend is turned on/off.

```python
ref_size = 1.25  # assume need .4 for legend
if legend_show:
    fig, axs = plt.subplots(
        2,
        figsize=(
            3.5,
            ref_size + 0.4,
        ), 
        sharex=True,
        gridspec_kw={
            "height_ratios": [0.4, ref_size + 0.4],
            "hspace": 0.01,
        }, 
    ax = axs[1]
else:
    fig, ax = plt.subplots(
        figsize=(3.5, ref_size)
    ) 
```
